# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  helloaspnetcore:
    image: helloaspnetcore
    build:
      context: .
      dockerfile: HelloAspNetCore/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=5142
    ports:
      - 5142:24
